name: first

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: envvvvv | sort
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: "Get-ChildItem Env: | Sort-Object Name"
    job3:
        name: "Third Job Depends on First Job and Second Job"
        needs: [job1, job2]
        runs-on: ubuntu-latest
        steps:
            - name: Get the Date info
              run: date 
